# Generated by Django 5.2.11 on 2026-02-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0002_change_product_status_choices'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'output'), _negated=True), ('customer__isnull', False), _connector='OR'), name='output_requires_customer'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'output'), _negated=True), ('sale__isnull', False), _connector='OR'), name='output_requires_sale'),
        ),
        migrations.AddConstraint(
            model_name='movement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('movement_type', 'input'), _negated=True), ('purchase__isnull', False), _connector='OR'), name='input_requires_purchase'),
        ),
    ]
